name: Test project

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20']

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: ./go.sum

      - name: Install dependencies
        run: go get ./...

      - name: Go vet
        run: go vet ./...

      - name: Run go test
        run: go test --race -v -coverprofile=coverage.txt ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

